# Generated by Django 2.0.2 on 2018-03-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aepp_auth', '0002_auto_20180323_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubuser',
            old_name='user_id',
            new_name='github_user_id',
        ),
    ]
