version: '3'

services:

  redis:
    image: redis
    volumes:
      - 'redisdata:/data'

  epoch:
    image: aetrnty/epoch
    env_file: .env
    environment:
      EPOCH_CONFIG: /home/epoch/epoch.yaml
    volumes:
      - ${PWD}/docker/epoch/epoch_config.yaml:/home/epoch/epoch.yaml
      - epochdb:/home/epoch/node/data/mnesia
      - node_keys:/home/epoch/node/keys
    ports:
      - "${EPOCH_PORT}:3013"

  web:
    build: .
    entrypoint: /code/docker/docker-entrypoint.sh
    env_file: .env
    environment:
      - EPOCH_KEYS_DIR=/epoch/keys
      - DATABASE_PATH=/db/
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - .:/code
      - 'cachedata:/cache'
      - node_keys:/epoch/keys
      - middleware_db:/db/
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:3.7
    env_file: .env
    environment:
      - RABBITMQ_USER=rabbitmq
    volumes:
      - ./docker/rabbitmq/docker-entrypoint.sh:/app/rabbitmq-entrypoint.sh
      - rabbit:/var/lib/rabbitmq


volumes:
  node_keys:
  middleware_db:
  epochdb:
  pgdata:
  redisdata:
  cachedata:
  rabbit:
