# Generated by Django 2.0.2 on 2018-03-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaucetTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(db_index=True, max_length=128)),
                ('amount', models.FloatField()),
                ('transfered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
