# Generated by Django 2.0.2 on 2018-03-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faucettransaction',
            old_name='transfered_at',
            new_name='transferred_at',
        ),
        migrations.AlterField(
            model_name='faucettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=24),
        ),
    ]
