# Generated by Django 2.0.2 on 2018-03-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faucettransaction',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faucettransaction',
            name='public_key',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
