# Generated by Django 2.0.2 on 2018-03-23 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_key', models.TextField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(default='PRECLAIMED', max_length=64)),
                ('claim_salt', models.CharField(max_length=64, null=True)),
                ('name_hash', models.CharField(max_length=64, null=True)),
                ('preclaim_tx', models.CharField(max_length=128, null=True)),
                ('claim_tx', models.CharField(max_length=128, null=True)),
                ('pointers', models.ManyToManyField(related_name='pointers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
