# Generated by Django 2.0.2 on 2018-03-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epoch_extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aename',
            name='status',
            field=models.CharField(default='PRECLAIMED', max_length=64),
        ),
    ]
