# Generated by Django 2.0.2 on 2018-03-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epoch_extra', '0002_aename_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aename',
            name='claim_salt',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aename',
            name='claim_tx',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='aename',
            name='name_hash',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='aename',
            name='preclaim_tx',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
